apiVersion: v1
kind: ConfigMap
metadata:
  name: partition-config
  namespace: default
data:
  db_host: "localhost"
  db_port: "3306"
  db_name: "atlas_db"
  # application.yml: |
  #   logging:
  #     level: info