apiVersion: v1
kind: Service
metadata:
  name: partition-manager
  namespace: default
  labels:
    app: partition-manager
spec:
  type: ClusterIP
  selector:
    app: partition-manager
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
